### ISSUE TITLE
Why the result looks like this: ResultStatus.UNKNOWN ?

### ISSUE THREAD

**Issue by AlyssonPHN** [LeonidVeremchuk/flutter-google-pay#2]
Why the result looks like this: 
error = null
data = null
status = ResultStatus.UNKNOWN ?

my code:
`  _makePayment() async {
    if (!(await FlutterGooglePay.isAvailable("test"))) {
      //_showToast(context, 'Google pay not available');
    } else {
      bool customData = false;
      if (!customData) {
        PaymentItem pm = PaymentItem(
            currencyCode: "usd",
            amount: "1.0",
            gateway: 'stripe'
        );
        FlutterGooglePay.makePayment(pm).then((Result result) {
          if (result.status == ResultStatus.SUCCESS) {
            //Success!
          }
        }).catchError((error) {
          //unresolved error
          print(error);
        });
      }
    }
  }`

**Comment by LeonidVeremchuk** [comment]
@AlyssonPHN Thank you for issue:

I do not updated the documentation in latest version.

Please add the stripe token and version:

"stripeToken": "pk_test_TYooMQauvdEDq54NiTphI7jx",
"stripeVersion":"2018-11-08"

Please let me know if not helped

**Comment by AlyssonPHN** [comment]
> Why the result looks like this:
> error = null
> data = null
> status = ResultStatus.UNKNOWN ?
> 
> my code:
> ` _makePayment() async { if (!(await FlutterGooglePay.isAvailable("test"))) { //_showToast(context, 'Google pay not available'); } else { bool customData = false; if (!customData) { PaymentItem pm = PaymentItem( currencyCode: "usd", amount: "1.0", gateway: 'stripe' ); FlutterGooglePay.makePayment(pm).then((Result result) { if (result.status == ResultStatus.SUCCESS) { //Success! } }).catchError((error) { //unresolved error print(error); }); } } }`



> "stripeToken": "pk_test_TYooMQauvdEDq54NiTphI7jx",
> "stripeVersion":"2018-11-08"

Perfect, Thanks!
