### ISSUE TITLE
Is it possible to change the gateway in PaymentItem?

### ISSUE THREAD

**Issue by AlyssonPHN** [LeonidVeremchuk/flutter-google-pay#3]
Is it possible to change the gateway in PaymentItem?

I also can not _makeCustomPayment run:

_makeCustomPayment() async {
    if (!(await FlutterGooglePay.isAvailable("test"))) {
      //_showToast(context, 'Google pay not available');
    } else {
      var jsonPayment = Map();
      jsonPayment["currencyCode"] =  "brl";
      jsonPayment["amount"] = "1.0";
      jsonPayment["gateway"] = "stripe";
      jsonPayment["stripeToken"] =  "pk_test_TYooMQauvdEDq54NiTphI7jx";
      jsonPayment["stripeVersion"] = "2018-11-08";

    `FlutterGooglePay.makeCustomPayment(jsonPayment).then((dynamic result) {
        if (result.status == ResultStatus.SUCCESS) {
          //Success!
        }
      }).catchError((error) {
        //unresolved error
      });
    }
  }`

**Comment by LeonidVeremchuk** [comment]
Hello @AlyssonPHN . Currently we have 2 way. 
1) Use PaymentItem  for stripe gateway
2) Create the JSON with all parameters. You need to follow the GooglePay sample. Tomorrow I will add the sample for custom payment way. 

Thank you for feedback.
